apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-jobs-api-2
  namespace: '831125582543'
  selfLink: /apis/serving.knative.dev/v1/namespaces/831125582543/services/spring-jobs-api-2
  uid: 58bb45ff-9be2-4fbd-b1f9-62841dea9760
  resourceVersion: AAY2hm0ngFI
  generation: 3
  labels:
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: europe-west2
  annotations:
    serving.knative.dev/creator: dineshm9987@gmail.com
    serving.knative.dev/lastModifier: dineshm9987@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: 283c5324-b581-4dd9-b408-0b4560be83e4
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://spring-jobs-api-2-831125582543.europe-west2.run.app"]'
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 53b85130-9ff8-4008-93ff-d9a533c88b55
        run.googleapis.com/startupProbeType: Custom
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: 831125582543-compute@developer.gserviceaccount.com
      containers:
        - name: campaign-manager-v3-1
          image: europe-west2-docker.pkg.dev/triple-student-461610-i1/spring-jobs-repo/campaign-manager-v3:test-2
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: triple-student-461610-i1
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          startupProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 2
            httpGet:
              path: /actuator/health/readiness
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true

