management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    diskspace:
      enabled: 'false'
    ssl:
      enabled: 'false'
  endpoint:
    health:
      probes:
        enabled: 'true'
server:
  port: '8080'

bigquery:
  project-id: triple-student-461610-i1
  dataset: hackathon1
  table: job_table

data-composer:
  env-id: composer-environment-id
  location: europe-west2
  project-id: triple-student-461610-i1
  dag-id: test123